# Site
repository: lusalas16/lusalas16.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Luis Carlos Salas Villalobos
title: Arquitecto de Software
email: lusalas16@gmail.com
website: https://luiscasalas16.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  luiscasalas16
linkedin_username: luiscasalas16
twitter_username: luiscasalas16
# instagram_username: luiscasalas16
# facebook_username: luiscasalas16

# About Section
about_title: Sobre Mí
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hola, mi nombre es Luis Carlos y soy Ingeniero en Computación. Actualmente ocupo el rol de Arquitecto de Software. Cuento con una experiencia profesional de más de 14 años en proyectos de desarrollo de software. He participado en proyectos de diversos tamaños, complejidades, duraciones, para empresas públicas y privadas.

  Soy organizado y entusiasta de la programación. Me gusta estudiar constantemente, aportar y aprender conocimientos, así como experiencias de mis compañeros de trabajo.

  Mi trabajo actual consiste en apoyar técnicamente varios proyectos de la empresa, haciendo propuestas técnicas de arquitecturas lógicas y físicas para aplicaciones, instalando infraestructuras en tierra y en nube, desarrollando arquitecturas, bases de datos, servicios, migradores, herramientas, especificadores, generadores, compiladores, intérpretes, firmadores, entre otros; además de apoyar a mis compañeros en la solución de problemas técnicos y realizar el manteniendo de un framework de desarrollo de aplicaciones de la empresa, que tiene diferentes versiones y ha sido utilizado en la construcción de varias aplicaciones en más de diez años de su existencia.

content:
  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Grupo Asesor
        link: www.grupoasesor.net
        sub_title: Arquitecto de Software
        caption: Diciembre 2008 - Presente
        description: | # this will include new lines to allow paragraphs
            Grupo Asesor en Informática es una empresa costarricense de desarrollo de soluciones a nivel mundial bajo un enfoque de calidad, innovación y agilidad a través de equipos de trabajo comprometidos en los que participan activamente sus clientes. En la empresa he participado en varios proyectos, entre ellos:
            - Framework de desarrollo de aplicaciones de Grupo Asesor, utilizado en los proyectos:
              - Instituto Costarricense de Investigación y Enseñanza en Nutrición y Salud, Sistema de información de laboratorio.
              - Instituto Costarricense de Investigación y Enseñanza en Nutrición y Salud, Sistema de registro de muestras.
              - Ministerio de Trabajo, Portal de centro de trabajo del Consejo de Salud Ocupacional.
              - Alimentos Prosalud, Sistema de evaluación de desempeño.
              - Ministerio de Obras Públicas y Transportes, Sistema de planificación institucional.
              - Ministerio de Educación Pública, Sistema de asignación de pecurso humano.
              - Ministerio de Educación Pública, Sistema de planificación institucional.
            - IPSUM Consultores, Sistema de planificación estratégica y operativa para organizaciones.
            - Asamblea Legislativa de Costa Rica, Framework de desarrollo de aplicaciones.
            - Promotora de Comercio Exterior de Costa Rica, Sistema de ventanilla única de comercio exterior.
            - Ministerio de Trabajo, Sistema de pensiones.
            - Ministerio de Hacienda, Sistema de recursos humanos, planillas y pagos.
            - Instituto Nacional de Seguros, Sistema de cotización y expedición de seguros.
            - Superintendencia General de Valores, Portal de la institución.
            - CIS-Group, Sistema de distribución.

  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UCR
        caption: 2013 - 2018
        sub_title: Maestría Profesional en Computación e Informática
        #quote: >
          #Universidad de Costa Rica
        description: | # this will include new lines to allow paragraphs
          Universidad de Costa Rica, estudios de grado. [+](https://pci.ucr.ac.cr/carrera/maestrí-profesional-en-computación-e-informática).
      - layout: left
        title: TEC
        caption: 2005 - 2009
        sub_title: Bachiller en Ingeniería en Computación
        #quote: >
          #Instituto Tecnológico de Costa Rica
        description: | # this will include new lines to allow paragraphs
          Instituto Tecnológico de Costa Rica, estudios de pregrado. [+](https://www.tec.ac.cr/programas-academicos/bachillerato-ingenieria-computacion).

  - title: Cursos y Certificaciones
    layout: text
    content: | # this will include new lines to allow paragraphs
      - GIT + GitHub: Todo un sistema de control de versiones de cero, 2023, 12 horas, Udemy, [certificado](https://www.udemy.com/certificate/UC-6a79af79-a685-4b3f-915b-fb9b119a05d8)
      - Azure Solutions Architect Expert, 06-2021 - 06-2023, Microsoft, [certificado](https://www.credly.com/badges/1f6ffd9a-cfb3-48be-9d9b-911feb661d81)
      - Microsoft Azure Architect Technologies (AZ-303), 06-2021, Microsoft
      - Microsoft Azure Architect Design (AZ-304), 08-2021, Microsoft

  - title: Portafolio # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Ejemplo .NET Framework - ASP.NET - WCF - DB
        link: https://github.com/luiscasalas16/example-netfw-asp-wcf-db
        link_text: repositorio
        description: | # this will include new lines to allow paragraphs
          Proyecto en el que una aplicación web (UI) invoca un servicio en wcf (WCF). El proyecto en wcf hace el acceso a la base de datos (DB) con un ensamblado independiente. Existe ensamblado compartido para las entidades (ENT).
      - layout: top-middle
        title: Ejemplo Básico Webpack
        link: https://luiscasalas16.github.io/example-webpack-js
        link_text: aplicación
        additional_links:
          - title:  repositorio
            icon: fab fa-github
            url: https://github.com/luiscasalas16/example-webpack-js
        description: | # this will include new lines to allow paragraphs
          royecto de ejemplo de configuración de Webpack 5.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

plugins:
 - jekyll-seo-tag