# Site
repository: lusalas16/lusalas16.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Luis Carlos Salas Villalobos
title: Arquitecto de Software
email: lusalas16@gmail.com
website: https://luiscasalas16.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  luiscasalas16
linkedin_username: luiscasalas16
twitter_username: luiscasalas16
# instagram_username: luiscasalas16
# facebook_username: luiscasalas16

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hola, mi nombre es Luis Carlos y soy Ingeniero en Computación. Actualmente ocupo el rol de Arquitecto de Software. Tengo una experiencia profesional de más de 14 años en proyectos de desarrollo de software. He participado en proyectos de diversos tamaños, complejidades, duraciones, para empresas públicas y privadas.

  Soy organizado y entusiasta de la programación. Me gusta estudiar constantemente y estar aportando y aprendiendo conocimientos y experiencias de mis compañeros de trabajo.

  Mi trabajo actual consiste en apoyar técnicamente varios proyectos de la empresa, haciendo propuestas técnicas de arquitecturas lógicas y físicas para aplicaciones, instalando infraestructuras en tierra y en nube, desarrollando arquitecturas, bases de datos, servicios, migradores, herramientas, especificadores, generadores, interpretes, firmadores, etc, además de apoyar a mis compañeros en la solución de problemas técnicos y manteniendo un framework de desarrollo de aplicaciones, que tiene múltiples versiones y ha sido utilizado para la construcción de varias aplicaciones transaccionales en más de 10 años de existencia.
  
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: Grupo Asesor en Informática
        link: https://www.grupoasesor.net/
        sub_title: Arquitecto de Software
        caption: Diciembre 2008 - Presente
 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
         description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

plugins:
 - jekyll-seo-tag
